---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuberos-config
  namespace: kube-system
data:
  template: |-
    apiVersion: v1
    kind: Config
    current-context: {{ .context }}
    clusters:
    - name: {{ .context }}
      cluster:
        certificate-authority-data: REDACTED
        server: https://api.{{ .context }}
