---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuberos
  namespace: kube-system
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - secretName: {{ .tlsSecret }}
      hosts:
        - {{ .hostname }}.{{ .domain }}
  rules:
    - host: {{ .hostname }}.{{ .domain }}
      http:
        paths:
        -  backend:
             serviceName: kuberos
             servicePort: 80
