---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kuberos
  name: kuberos
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 10003
  selector:
    k8s-app: kuberos
